language: elixir
elixir:
  - 1.8
otp_release:
  - 21.0
matrix:
  include:
    - elixir: 1.9
      otp_release: 21.0
    - elixir: 1.10
      otp_release: 21.0
before_script:
  - mix deps.get
script:
  - mix test
