language: elixir
elixir:
- 1.8
otp_release:
- 21.0
matrix:
  include:
  - elixir: 1.9
    otp_release: 21.0
  - elixir: 1.1
    otp_release: 21.0
before_script:
- mix deps.get
script:
- mix test
notifications:
  slack:
    rooms:
      secure: SlvqgnUV1oE/oLgGJmD4Bz+l14g+wOnsswOFVUSFyJ8ABJotMShqYwKKIW/A+himOgfX4U0TtOMeenJQVbG4AneNhpOWC6evxIyYkZ5X21AoxZpcm0bV3Tqm+pRzaTfdKgYYkmYVHazOHBIjzSOUjDjnqM6ZOA6C5FNU9FBnUnsVF7kgJHJEYn+ZYedMW8SEPW5FIz1d04Zr5eGSuVQqDx6SSG8Kcp05hEw6i0Z0+4vWpv2HT1Pw1cXKKjvg6YwwDuzDTMOLAhBioT1Bm7Lz0nHznebp/w5vxTsuXzo+E0jA7F6ks2UgQGYmrL1mVRg5LMBebsDNzfOYsRjXKYOwwdI/J04Y4iHVclPCT/rgbP66xAB44qulhoM6RdeC2ECEGAHzFY4zbcRedGgK63YTTa7BVhW09MD2KhtWrdjBxJgHSUO9M1D87969PTwJ0yA1Uz9wVcf3Dsc7mrBAM0z8HhMPeTCHExJXbqsllh4SmmqBGlUdetRF5Z1+Smhy5Mqe0c9sWogPpVV52NRASlMsy6R6OsXJJ01sONRsq4PG9QX/YbMg/l+U0rZpIOQG4GlqUvtNajJvDUy4JKd14jp27bsMAASYNBWtGh90TE0m0wncm3sGGXKLUKSkIF798YQrqIFeLPLTqv9DjFvGP5C2Fcl/DHpAGQ8Sl0HQK0QuMTI=
